spring:
  application:
    name: springboot-template

# TODO MySQL相关配置
  datasource:
    url: jdbc:mysql://localhost:3306/common
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

# TODO Redis相关配置
  redis:
    # Redis服务器连接端口
    host:
    # Redis数据库索引
    database: 1
    port: 6379
    # 连接超时时间
    timeout: 5s
    password:
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

server:
  port: 8080
  servlet:
    context-path: /api

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印sql
  global-config:
    db-config:
      logic-not-delete-value: 1 # mybatis-plus 逻辑删除

knife4j:
  enable: true
  openapi:
    title: springboot-template_backend
    description: 后端接口文档
    email: dhx2648466390@163.com
    concat: adorabled4
    url: https://blog.dhx.icu
    version: v4.0
    license: Apache 2.0
    license-url: https://blog.dhx.icu
    terms-of-service-url: https://blog.dhx.icu
    group:
      dev:
        group-name: dev
        api-rule: package
        api-rule-resources:
          - com.dhx.template.controller

logging:
  config: classpath:logback.xml # 日志配置文件

# TODO 阿里云 sms
sms:
  endpoint: dysmsapi.aliyuncs.com
  accessId:
  accessKey:
# 线程池配置
template:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
